
#Config version identifier
config-version: 2
#Language
lang: "en"

# Enable economy functionality
enable-economy: false

# To allow mob to be used on spawner, add it here with value 0
mobs:
  # Zombie will be allowed here for $10
  # If you didn't enable economy functionality, 
  # you still need to put a cost value, and that value will be ignored.
  ZOMBIE: 
    econ-cost: 10
    item-costs:
    - DIAMOND 1
