
#Config version identifier
config-version: 2
#Language
lang: "zh-cn"

# Enable economy functionality
enable-economy: false

# To allow mob to be used on spawner, add it here with value 0
mobs:
  # Zombie will be allowed here for $10
  ZOMBIE: 10
