
#Config version identifier
config-version: 1
#Permission Switch
enable-permission: true
#Language
lang: "en"

allowed-mobs:
  - allay
  - axolotl
  - bat
  - bee
  - blaze
  - cat
  - camel
  - cave-spider
  - chicken
  - cod
  - cow
  - creeper
  - dolphin
  - donkey
  - drowned
  - elder-guardian
  - ender-dragon
  - enderman
  - endermite
  - evoker
  - fox
  - frog
  - ghast
  - glow-squid
  - goat
  - guardian
  - hoglins
  - horse
  - husk
  - iron-golem
  - llama
  - magma-cube
  - mooshroom
  - mule
  - ocelot
  - panda
  - parrot
  - phantom
  - pig
  - piglin
  - piglin-brute
  - pillager
  - polar-bear
  - pufferfish
  - rabbit
  - ravager
  - salmon
  - sheep
  - shulker
  - silverfish
  - skeleton
  - skeleton-horse
  - slime
  - sniffer
  - snow-golem
  - spider
  - squid
  - stray
  - strider
  - tadpole
  - trader-llama
  - tropical-fish
  - turtle
  - vex
  - villager
  - vindicator
  - wandering-trader
  - warden
  - witch
  - wither
  - wither-skeleton
  - wolf
  - zoglin
  - zombie
  - zombie-horse
  - zombie-villager
  - zombified-piglin