name: SpawnerManager
main: me.henrydhc.spawnermanager.SpawnerManager
version: 1.1.0-BETA
api-version: 1.20
description: Control players' access to spawners.
permissions:
  use:
    description: Allows player to interact with spawners.
    default: true
  reload:
    description: Allows user to reload the plugin
    default: op
  bypass:
    description: Allow user to bypass spawner restriction.
    default: false
  set:
    description: Allow user to set whether a mob egg can be used on spawner
    default: op

commands:
  spawnermanager:
    aliases:
      - sm
    usage: /spawnermanager <options>
    permission-message: You don't have permission to execute this command!