name: SpawnerManager
main: me.henrydhc.spawnermanager.SpawnerManager
version: 1.0-SNAPSHOT
api-version: 1.20
description: Control players' access to spawners.
permissions:
  use:
    description: Allows player to interact with spawners.
    default: false
  admin:
    description: Allows user to execute admin commands
    default: op

commands:
  spawnermanager:
    aliases:
      - sm
    usage: /spawnermanager <options>
    permission: admin
    permission-message: You don't have permission to execute this command!